version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "bun"
    directory: "/packages/webapp"
    schedule:
      interval: "monthly"

  - package-ecosystem: "bun"
    directory: "/packages/scraper"
    schedule:
      interval: "monthly"

  - package-ecosystem: "bun"
    directory: "/packages/server"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
