name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p $HOME/.local
      # https://github.com/bmizerany/setup-postgres?tab=readme-ov-file#environment-configuration
      - uses: bmizerany/setup-postgres@v3
      - uses: actions/checkout@v6

        # with:
        #   postgresql version: "15"
        #   postgresql db: "pr-counts"
        #   postgresql username: "postgres"
        #   postgresql password: "postgres"
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
      - run: bun run tsc
      - run: bun run --filter scraper migrate
      - run: bun run --filter webapp build
